import { StyleSheet } from "react-native";
import { F } from "../../theme/fonts";

export const CORNER_SIZE = 24;
export const CORNER_THICKNESS = 3;

export const styles = StyleSheet.create({
  chooseContainer: {
    flex: 1,
  },
  chooseHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 6,
    borderBottomWidth: 1,
  },
  chooseTitle: {
    fontFamily: F.sans600,
    fontSize: 17,
  },
  chooseBody: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    gap: 14,
  },
  chooseSubtitle: {
    fontFamily: F.sans400,
    fontSize: 14,
    marginBottom: 8,
    lineHeight: 20,
  },
  chooseOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    gap: 14,
  },
  chooseOptionIcon: {
    width: 52,
    height: 52,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  chooseOptionText: {
    flex: 1,
    gap: 3,
  },
  chooseOptionTitle: {
    fontFamily: F.sans600,
    fontSize: 15,
  },
  chooseOptionDesc: {
    fontFamily: F.sans400,
    fontSize: 13,
  },
  galleryContainer: {
    flex: 1,
  },
  galleryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
  },
  previewImage: {
    flex: 1,
    width: "100%",
  },
  galleryStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    margin: 16,
    padding: 14,
    borderRadius: 12,
  },
  galleryStatusText: {
    fontFamily: F.sans400,
    fontSize: 14,
    flex: 1,
  },
  cameraContainer: {
    flex: 1,
    backgroundColor: "black",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
  },
  cameraHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 6,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  cameraHeaderTitle: {
    color: "white",
    fontFamily: F.sans600,
    fontSize: 17,
  },
  viewfinderWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  viewfinder: {
    width: 220,
    height: 220,
    position: "relative",
  },
  corner: {
    position: "absolute",
    width: CORNER_SIZE,
    height: CORNER_SIZE,
    borderColor: "white",
  },
  cornerTL: { top: 0, left: 0, borderTopWidth: CORNER_THICKNESS, borderLeftWidth: CORNER_THICKNESS, borderTopLeftRadius: 4 },
  cornerTR: { top: 0, right: 0, borderTopWidth: CORNER_THICKNESS, borderRightWidth: CORNER_THICKNESS, borderTopRightRadius: 4 },
  cornerBL: { bottom: 0, left: 0, borderBottomWidth: CORNER_THICKNESS, borderLeftWidth: CORNER_THICKNESS, borderBottomLeftRadius: 4 },
  cornerBR: { bottom: 0, right: 0, borderBottomWidth: CORNER_THICKNESS, borderRightWidth: CORNER_THICKNESS, borderBottomRightRadius: 4 },
  scanHint: {
    marginTop: 24,
    color: "rgba(255,255,255,0.8)",
    fontFamily: F.sans400,
    fontSize: 14,
    textAlign: "center",
  },
  closeBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  resultPanel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 12,
  },
  resultHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 16,
  },
  resultHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  resultIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: "center",
    alignItems: "center",
  },
  resultTitle: {
    fontFamily: F.sans700,
    fontSize: 17,
    marginBottom: 2,
  },
  resultSubtitle: {
    fontFamily: F.sans400,
    fontSize: 13,
  },
  fieldsBox: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 12,
    marginBottom: 16,
    gap: 8,
  },
  fieldRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  fieldLabel: {
    fontFamily: F.sans400,
    fontSize: 13,
  },
  fieldValue: {
    fontFamily: F.sans600,
    fontSize: 13,
    flex: 1,
  },
  rawDataText: {
    fontFamily: F.sans400,
    fontSize: 12,
    lineHeight: 18,
  },
  fillButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    borderRadius: 16,
    marginBottom: 10,
    shadowColor: "#A35830",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  fillButtonText: {
    color: "white",
    fontFamily: F.sans600,
    fontSize: 16,
  },
  rescanButton: {
    alignItems: "center",
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 4,
  },
  rescanButtonText: {
    fontFamily: F.sans500,
    fontSize: 15,
  },
  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
    gap: 16,
  },
  permissionTitle: {
    fontFamily: F.sans700,
    fontSize: 20,
    textAlign: "center",
  },
  permissionSubtitle: {
    fontFamily: F.sans400,
    fontSize: 15,
    textAlign: "center",
    lineHeight: 22,
  },
  primaryButton: {
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 8,
  },
  primaryButtonText: {
    color: "white",
    fontFamily: F.sans600,
    fontSize: 16,
  },
  linkButton: {
    paddingVertical: 10,
  },
  linkButtonText: {
    fontFamily: F.sans400,
    fontSize: 15,
  },
});
